AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.6.3

Rails:
  Enabled: true

FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'config/routes.rb'
Naming/MethodName:
  Exclude:
    - 'app/concepts/**/lib/macro.rb'
Style/Lambda:
  Exclude:
    - 'app/concepts/**/lib/macro/*.rb'
