name: Transition jira issue
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: "FR-2444"
        transition: "In Progress"
