name: Add Labels1
on: pull_request_review

jobs:
  add_labels:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.event.review.state }}"
    - uses: actions-ecosystem/action-add-labels@v1
      if: github.event.review.state == 'changes_requested'
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        labels: bug
    - uses: actions-ecosystem/action-add-labels@v1
      if: github.event.review.state == 'approved'
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        labels: ok
    - uses: actions-ecosystem/action-remove-labels@v1
      if: github.event.review.state == 'changes_requested'
      with:
        github_token: ${{ secrets.github_token }}
        labels: ok
    - uses: actions-ecosystem/action-remove-labels@v1
      if: github.event.review.state == 'approved'
      with:
        github_token: ${{ secrets.github_token }}
        labels: bug
